
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 155
#define YY_END_OF_BUFFER 156
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[335] =
    {   0,
        0,    0,    0,    0,    0,    0,  156,  154,    1,  153,
      115,   87,  127,  117,  112,   70,  108,  109,  113,  104,
      126,  105,  110,  116,   52,   40,  123,  124,  118,  125,
      119,  122,   39,  150,  152,  111,  120,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,  106,  121,  107,  114,  127,  155,   86,
       71,   82,  103,   88,   99,    1,  136,  142,  137,  147,
      140,  129,  143,  130,  144,  128,    0,   58,  141,   58,
       52,    0,    0,   54,   53,   46,   54,   40,   42,   41,
       42,  131,  133,  135,  134,  132,   39,  152,  149,   39,

       39,   39,   39,   39,   39,   39,   39,   39,    9,   39,
       39,   39,   39,   39,   39,   17,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,  148,  138,    0,
       81,   80,   72,   84,   83,   73,   74,   75,   76,   77,
       78,   79,    0,   98,   97,   89,  101,  100,   90,   91,
       92,   93,   94,   95,   96,    0,  139,    0,   59,   60,
        0,   61,   55,   56,   56,   56,   46,   48,   47,   48,
       43,   44,   44,   44,  145,  146,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       15,   39,   39,   19,   39,   39,   39,   39,   39,   39,

       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
        0,   85,  102,    0,   58,   62,   63,   57,    0,   46,
        0,   49,   50,   50,   50,   45,   39,   39,   39,    2,
       39,    4,    5,   39,   39,   39,   39,   11,   12,   39,
       39,   16,   39,   20,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   33,   39,   39,    0,
        0,    0,    0,   67,   51,   36,   39,   39,    3,    6,
       39,   39,   39,   39,   14,   39,   39,   39,   39,   24,
       39,   39,   39,   39,   39,   39,   31,   39,   39,   35,
      151,    0,   64,   68,   69,   39,   39,   39,   39,   10,

       13,   18,   39,   39,   23,   25,   26,   27,   28,   29,
       39,   39,   39,   65,   66,   39,   39,   39,    8,   39,
       39,   30,   39,   39,   37,   39,    7,   21,   22,   32,
       34,   39,   38,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   28,   31,   32,
       33,   33,   34,   33,   33,   35,   33,   33,   33,   33,
       33,   33,   33,   33,   36,   33,   33,   37,   33,   33,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   33,   52,   53,   54,   55,
       56,   57,   33,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    4,    4,
        4,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        4,    4,    5,    5,    6,    6,    5,    1,    1,    1,
        1,    5,    4,    4,    4,    4,    4,    4,    5,    5,
        5,    5,    6,    5,    5,    5,    7,    5,    5,    5,
        6,    5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[345] =
    {   0,
        0,  540,   70,   73,   76,   88,  546,  548,   83,  548,
      520,  548,  548,  519,   72,  548,  548,  548,  518,   70,
      548,   76,   86,  517,  111,  102,  548,  548,   89,  516,
       91,  548,    0,  548,    0,  548,  515,   95,  478,  480,
      100,   79,   81,   88,  481,  104,  480,  488,  110,  469,
      478,  476,  481,  548,   83,  548,  548,  526,  548,  548,
      548,  170,  548,  548,  229,  116,  548,  548,  548,  548,
      548,  548,  548,  548,  548,  548,  512,  146,  548,  189,
      233,  165,  184,  118,  104,  166,  170,  278,  156,  134,
      180,  503,  548,  548,  548,  502,    0,    0,  548,  470,

      469,  470,  463,  475,  462,  477,  464,  470,  456,  457,
      454,  454,  457,  454,  451,    0,  135,  455,  198,  453,
      177,  125,  457,  450,  156,  187,  455,  548,  548,  225,
      548,  548,  240,  242,  548,  548,  548,  548,  548,  548,
      548,  548,    0,  548,  548,  246,  251,  548,  548,  548,
      548,  548,  548,  548,  548,    0,  548,  262,  548,  548,
      281,  284,  227,  548,  470,  451,  291,  275,  232,  254,
      256,  548,  468,  449,  548,  548,  445,  446,  456,  442,
      454,  449,  437,  215,  451,  449,  445,  437,  443,  446,
        0,  432,  436,    0,  437,  434,  424,  422,  424,  426,

      433,  419,  417,  417,  429,  419,  423,  427,  429,  418,
      302,    0,    0,  309,  314,  548,  548,  548,  413,  307,
      337,  284,  548,  434,  415,  548,  414,  409,  416,    0,
      407,    0,    0,  396,  404,  390,  394,    0,    0,  382,
      359,    0,  363,    0,  358,  358,  355,  352,  364,  354,
      357,  362,  361,  359,  349,  354,    0,  341,  353,    0,
      341,  355,  358,  361,  548,    0,  344,  344,    0,    0,
      339,  339,  344,  335,    0,  342,  313,  321,  315,    0,
      320,  317,  318,  301,  309,  308,    0,  299,  299,    0,
        0,  364,  367,  548,  548,  300,  286,  279,  278,    0,

        0,    0,  271,  267,    0,    0,    0,    0,    0,    0,
      248,  232,  202,  548,  548,  187,  179,  164,    0,  116,
      111,    0,  116,   93,    0,   52,    0,    0,    0,    0,
        0,   39,    0,  548,  420,  427,  431,  438,  442,   96,
       84,  446,  450,  457
    } ;

static yyconst flex_int16_t yy_def[345] =
    {   0,
      334,    1,  335,  335,  336,  336,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  337,  334,  338,  334,  334,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  339,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  337,  338,  334,  337,

      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  340,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  341,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  342,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,

      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      334,  340,  341,  334,  334,  334,  334,  334,  343,  342,
      334,  334,  334,  334,  334,  334,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  344,
      334,  334,  334,  334,  334,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      344,  334,  334,  334,  334,  337,  337,  337,  337,  337,

      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  334,  334,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,    0,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334
    } ;

static yyconst flex_uint16_t yy_nxt[619] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       26,   27,   28,   29,   30,   31,   32,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   33,
       46,   33,   47,   33,   33,   33,   33,   48,   49,   50,
       51,   52,   53,   33,   33,   33,   54,   55,   56,   57,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   61,
       69,   64,   61,   72,   66,   59,   66,  213,   59,   59,
       59,   74,   59,   64,   73,   59,   70,   59,   59,  212,

       75,   76,   77,  333,   78,   78,   78,  128,   62,  332,
       59,   62,   92,   93,   65,   95,   96,   66,   80,   66,
       88,   88,   88,  100,  101,  108,   65,   80,  102,   81,
       81,   82,   83,  110,  109,  111,   89,   90,  165,  331,
      113,   83,  105,  114,  112,   84,   85,   86,   83,  106,
      129,  116,  163,  164,   91,  107,  166,   83,  117,  120,
      121,  330,   90,   87,   78,   78,   78,  202,  173,  122,
      329,   85,  123,  328,   86,  131,  158,  159,  164,  132,
      160,   80,  203,   82,   82,   82,  174,  193,  133,  134,
      171,  172,  158,  159,  194,   83,  135,  161,  160,  161,

      168,  169,  162,  162,  162,  164,  206,   78,   78,   78,
      327,   83,  136,  137,  207,  172,  172,  138,  170,  158,
      159,  326,  163,  160,  139,  200,  169,  140,  130,  141,
      164,  142,  171,  143,  144,  158,  159,  208,  145,  209,
      172,  160,  201,  211,  211,  211,  196,  146,  147,   80,
      325,   81,   81,   82,  324,  148,  197,  198,  134,  134,
      134,  134,  218,   83,  147,  147,  224,   84,   85,  147,
      147,  149,  150,  234,  235,  214,  151,  214,  323,   83,
      215,  215,  215,  152,  225,   87,  153,  218,  154,  223,
      155,  226,  156,   85,   80,  322,   88,   88,   88,  162,

      162,  162,  162,  162,  162,  260,  222,  219,   83,  222,
      223,  321,   89,   90,  223,  216,  226,  320,  217,  265,
      211,  211,  211,  261,   83,  168,  169,  215,  215,  215,
       91,  216,  215,  215,  215,  223,  217,  319,   90,  318,
      317,  168,  169,  170,  265,  159,  316,  221,  160,  313,
      263,  169,  263,  312,  311,  264,  264,  264,  310,  170,
      309,  159,  308,  221,  307,  306,  160,  169,  292,  305,
      292,  304,  303,  293,  293,  293,  264,  264,  264,  264,
      264,  264,  293,  293,  293,  293,  293,  293,  302,  301,
      300,  299,  294,  298,  297,  295,  296,  262,  314,  290,

      289,  315,  288,  287,  286,  285,  284,  283,  294,  282,
      281,  280,  279,  295,  314,  278,  277,  276,  275,  315,
       60,   60,   60,   60,   60,   60,   60,   63,   63,   63,
       63,   63,   63,   63,   97,   97,   97,   97,   98,  274,
       98,   98,   98,   98,   98,  167,  273,  167,  220,  220,
      272,  220,  220,  261,  271,  270,  261,  291,  269,  291,
      291,  291,  291,  291,  268,  267,  266,  265,  265,  262,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  233,  232,  231,  230,  229,  228,

      227,  226,  226,  218,  218,  210,  205,  204,  199,  195,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  157,  130,
      127,  126,  125,  124,  119,  118,  115,  104,  103,   99,
       94,   79,   71,   68,   67,  334,   58,    7,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334
    } ;

static yyconst flex_int16_t yy_chk[619] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    4,    4,    4,    5,    5,    5,    3,
       15,    5,    4,   20,    9,    5,    9,  341,    6,    6,
        6,   22,    3,    6,   20,    4,   15,    6,    5,  340,

       22,   22,   23,  332,   23,   23,   23,   55,    3,  326,
        6,    4,   29,   29,    5,   31,   31,   66,   26,   66,
       26,   26,   26,   38,   38,   42,    6,   25,   38,   25,
       25,   25,   26,   43,   42,   43,   26,   26,   85,  324,
       44,   25,   41,   44,   43,   25,   25,   25,   26,   41,
       55,   46,   84,   84,   26,   41,   85,   25,   46,   49,
       49,  323,   26,   25,   78,   78,   78,  122,   90,   49,
      321,   25,   49,  320,   25,   62,   78,   78,   84,   62,
       78,   82,  122,   82,   82,   82,   90,  117,   62,   62,
       89,   89,   78,   78,  117,   82,   62,   83,   78,   83,

       86,   86,   83,   83,   83,   87,  125,   80,   80,   80,
      318,   82,   62,   62,  125,   91,   89,   62,   86,   80,
       80,  317,   87,   80,   62,  121,   86,   62,  130,   62,
       87,   62,   91,   62,   65,   80,   80,  126,   65,  126,
       91,   80,  121,  130,  130,  130,  119,   65,   65,   81,
      316,   81,   81,   81,  313,   65,  119,  119,  133,  133,
      134,  134,  163,   81,  146,  146,  169,   81,   81,  147,
      147,   65,   65,  184,  184,  158,   65,  158,  312,   81,
      158,  158,  158,   65,  169,   81,   65,  163,   65,  170,
       65,  171,   65,   81,   88,  311,   88,   88,   88,  161,

      161,  161,  162,  162,  162,  211,  170,  167,   88,  168,
      168,  304,   88,   88,  170,  162,  171,  303,  162,  222,
      211,  211,  211,  220,   88,  167,  167,  214,  214,  214,
       88,  162,  215,  215,  215,  168,  162,  299,   88,  298,
      297,  220,  220,  167,  222,  215,  296,  167,  215,  289,
      221,  167,  221,  288,  286,  221,  221,  221,  285,  220,
      284,  215,  283,  220,  282,  281,  215,  220,  262,  279,
      262,  278,  277,  262,  262,  262,  263,  263,  263,  264,
      264,  264,  292,  292,  292,  293,  293,  293,  276,  274,
      273,  272,  264,  271,  268,  264,  267,  261,  293,  259,

      258,  293,  256,  255,  254,  253,  252,  251,  264,  250,
      249,  248,  247,  264,  293,  246,  245,  243,  241,  293,
      335,  335,  335,  335,  335,  335,  335,  336,  336,  336,
      336,  336,  336,  336,  337,  337,  337,  337,  338,  240,
      338,  338,  338,  338,  338,  339,  237,  339,  342,  342,
      236,  342,  342,  343,  235,  234,  343,  344,  231,  344,
      344,  344,  344,  344,  229,  228,  227,  225,  224,  219,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  193,  192,  190,  189,
      188,  187,  186,  185,  183,  182,  181,  180,  179,  178,

      177,  174,  173,  166,  165,  127,  124,  123,  120,  118,
      115,  114,  113,  112,  111,  110,  109,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   96,   92,   77,   58,
       53,   52,   51,   50,   48,   47,   45,   40,   39,   37,
       30,   24,   19,   14,   11,    7,    2,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 4 "lexer.l"
    // DEFINITIONS
    #include "parse.tab.h"
    #include <stdlib.h>
    #define YY_DECL int yylex()
    #define OCT_OUT_OF_RANGE 1
    int line_num;
    int char_size;
    char *fname;
    char *char_ind;
    char char_buffer[4096];
    YYSTYPE yylval;

enum constants_numberspec{
    C_REAL = 0,
    C_INTEGER,
};

enum constants_sizespec{
    C_FLOAT = 1,
    C_DOUBLE,
    C_LONGDOUBLE,
    C_INT,
    C_LONG,
    C_LONGLONG,
};

char* tokens_names[60] = {"INDSEL","PLUSPLUS","MINUSMINUS","SHL","SHR","LTEQ","GTEQ","EQEQ",
                          "NOTEQ","LOGAND","LOGOR","ELLIPSIS","TIMESEQ","DIVEQ","MODEQ","PLUSEQ",
                          "MINUSEQ","SHLEQ","SHREQ","ANDEQ","OREQ","XOREQ","PDPD","AUTO",
                          "BREAK","CASE","CHAR","CONST","CONTINUE","DEFAULT","DO","DOUBLE",
                          "ELSE","ENUM","EXTERN","FLOAT","FOR","GOTO","IF","INLINE","INT",
                          "LONG","REGISTER","RESTRICT","RETURN","SHORT","SIGNED","SIZEOF",
                          "STATIC","STRUCT","SWITCH","TYPEDEF","UNION","UNSIGNED","VOID",
                          "VOLATILE","WHILE","_BOOL","_COMPLEX","_IMAGINARY"};


#line 755 "lex.yy.c"

#define INITIAL 0
#define BEGIN_CHAR 1
#define BEGIN_STR 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 48 "lexer.l"


    // RULES

#line 983 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 335 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 548 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 52 "lexer.l"
{}
	YY_BREAK

    // KEYWORDS

case 2:
YY_RULE_SETUP
#line 56 "lexer.l"
{return AUTO;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 57 "lexer.l"
{return BREAK;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 58 "lexer.l"
{return CASE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 59 "lexer.l"
{return CHAR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 60 "lexer.l"
{return CONST;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 61 "lexer.l"
{return CONTINUE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 62 "lexer.l"
{return DEFAULT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 63 "lexer.l"
{return DO;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 64 "lexer.l"
{return DOUBLE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 65 "lexer.l"
{return ELSE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 66 "lexer.l"
{return ENUM;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "lexer.l"
{return EXTERN;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 68 "lexer.l"
{return FLOAT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 "lexer.l"
{return FOR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 70 "lexer.l"
{return GOTO;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 71 "lexer.l"
{return IF;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 72 "lexer.l"
{return INLINE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 73 "lexer.l"
{return INT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 74 "lexer.l"
{return LONG;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 75 "lexer.l"
{return REGISTER;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 76 "lexer.l"
{return RESTRICT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 77 "lexer.l"
{return RETURN;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 78 "lexer.l"
{return SHORT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 79 "lexer.l"
{return SIGNED;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 80 "lexer.l"
{return SIZEOF;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 "lexer.l"
{return STATIC;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 82 "lexer.l"
{return STRUCT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 83 "lexer.l"
{return SWITCH;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 84 "lexer.l"
{return TYPEDEF;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 85 "lexer.l"
{return UNION;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 "lexer.l"
{return UNSIGNED;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 87 "lexer.l"
{return VOID;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "lexer.l"
{return VOLATILE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 "lexer.l"
{return WHILE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 "lexer.l"
{return _BOOL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 "lexer.l"
{return _COMPLEX;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 "lexer.l"
{return _IMAGINARY;}
	YY_BREAK

    // IDENTIFIERS

case 39:
YY_RULE_SETUP
#line 98 "lexer.l"
{yylval.ident_name = (char*) malloc(sizeof(yytext)+1); 
                        strcpy(yylval.ident_name, yytext);
                        return IDENT;}
	YY_BREAK

    // NUMERICAL CONSTANTS

case 40:
YY_RULE_SETUP
#line 106 "lexer.l"
{yylval.number.number=  strtol(yytext, NULL, 10);
                        yylval.number.num_numberspec = C_INTEGER; 
                        yylval.number.num_sizespec = C_INT;
                        yylval.number.num_unsigned = 0;
                        return NUMBER;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 112 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 10);
                      yylval.number.num_numberspec = C_INTEGER;
                      yylval.number.num_sizespec = C_INT;
                      yylval.number.num_unsigned = 1;
                      return NUMBER;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 118 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 10);
                     yylval.number.num_numberspec = C_INTEGER;
                     yylval.number.num_sizespec = C_LONG;
                     yylval.number.num_unsigned = 0;
                     return NUMBER;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 124 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 10);
                            yylval.number.num_numberspec = C_INTEGER;
                            yylval.number.num_sizespec = C_LONGLONG;
                            yylval.number.num_unsigned = 0;
                            return NUMBER;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 130 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 10);
                                        yylval.number.num_numberspec = C_INTEGER;
                                        yylval.number.num_sizespec = C_LONG;
                                        yylval.number.num_unsigned = 1;
                                        return NUMBER;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 136 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 10);
                                                     yylval.number.num_numberspec = C_INTEGER;
                                                     yylval.number.num_sizespec = C_LONGLONG;
                                                     yylval.number.num_unsigned = 1;
                                                     return NUMBER;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 142 "lexer.l"
{yylval.number.number=  strtol(yytext, NULL, 16);
                              yylval.number.num_numberspec = C_INTEGER; 
                              yylval.number.num_sizespec = C_INT;
                              yylval.number.num_unsigned = 0;
                              return NUMBER;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 148 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 16);
                            yylval.number.num_numberspec = C_INTEGER;
                            yylval.number.num_sizespec = C_INT;
                            yylval.number.num_unsigned = 1;
                            return NUMBER;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 154 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 16);
                           yylval.number.num_numberspec = C_INTEGER;
                           yylval.number.num_sizespec = C_LONG;
                           yylval.number.num_unsigned = 0;
                           return NUMBER;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 160 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 16);
                                  yylval.number.num_numberspec = C_INTEGER;
                                  yylval.number.num_sizespec = C_LONGLONG;
                                  yylval.number.num_unsigned = 0;
                                  return NUMBER;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 166 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 16);
                                              yylval.number.num_numberspec = C_INTEGER;
                                              yylval.number.num_sizespec = C_LONG;
                                              yylval.number.num_unsigned = 1;
                                              return NUMBER;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 172 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 16);
                                                           yylval.number.num_numberspec = C_INTEGER;
                                                           yylval.number.num_sizespec = C_LONGLONG;
                                                           yylval.number.num_unsigned = 1;
                                                           return NUMBER;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 178 "lexer.l"
{yylval.number.number=  strtol(yytext, NULL, 8);
                    yylval.number.num_numberspec = C_INTEGER; 
                    yylval.number.num_sizespec = C_INT;
                    yylval.number.num_unsigned = 0;
                    return NUMBER;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 184 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 8);
                  yylval.number.num_numberspec = C_INTEGER;
                  yylval.number.num_sizespec = C_INT;
                  yylval.number.num_unsigned = 1;
                  return NUMBER;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 190 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 8);
                 yylval.number.num_numberspec = C_INTEGER;
                 yylval.number.num_sizespec = C_LONG;
                 yylval.number.num_unsigned = 0;
                 return NUMBER;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 196 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 8);
                        yylval.number.num_numberspec = C_INTEGER;
                        yylval.number.num_sizespec = C_LONGLONG;
                        yylval.number.num_unsigned = 0;
                        return NUMBER;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 202 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 8);
                                    yylval.number.num_numberspec = C_INTEGER;
                                    yylval.number.num_sizespec = C_LONG;
                                    yylval.number.num_unsigned = 1;
                                    return NUMBER;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 208 "lexer.l"
{yylval.number.number = strtol(yytext, NULL, 8);
                                                 yylval.number.num_numberspec = C_INTEGER;
                                                 yylval.number.num_sizespec = C_LONGLONG;
                                                 yylval.number.num_unsigned = 1;
                                                 return NUMBER;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 214 "lexer.l"
{sscanf(yytext,"%Lf",&yylval.number.doub_number);
                                                   yylval.number.num_numberspec = C_REAL; 
                                                   yylval.number.num_sizespec = C_DOUBLE;
                                                   return NUMBER;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 219 "lexer.l"
{sscanf(yytext,"%Lf",&yylval.number.doub_number);
                                                       yylval.number.num_numberspec = C_REAL; 
                                                       yylval.number.num_sizespec = C_FLOAT;
                                                       return NUMBER;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 224 "lexer.l"
{sscanf(yytext,"%Lf",&yylval.number.doub_number);
                                                       yylval.number.num_numberspec = C_REAL; 
                                                       yylval.number.num_sizespec = C_LONGDOUBLE;
                                                       return NUMBER;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 229 "lexer.l"
{sscanf(yytext,"%Lf", &yylval.number.doub_number);
                          yylval.number.num_numberspec = C_REAL;
                          yylval.number.num_sizespec = C_DOUBLE;
                          return NUMBER;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 234 "lexer.l"
{sscanf(yytext,"%Lf", &yylval.number.doub_number);
                              yylval.number.num_numberspec = C_REAL;
                              yylval.number.num_sizespec = C_FLOAT;
                              return NUMBER;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 239 "lexer.l"
{sscanf(yytext,"%Lf", &yylval.number.doub_number);
                              yylval.number.num_numberspec = C_REAL;
                              yylval.number.num_sizespec = C_LONGDOUBLE;
                              return NUMBER;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 244 "lexer.l"
{sscanf(yytext,"%Lf",&yylval.number.doub_number);
                                                                     yylval.number.num_numberspec = C_REAL;
                                                                     yylval.number.num_sizespec = C_DOUBLE;
                                                                     return NUMBER;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 249 "lexer.l"
{sscanf(yytext,"%Lf",&yylval.number.doub_number);
                                                                         yylval.number.num_numberspec = C_REAL;
                                                                         yylval.number.num_sizespec = C_FLOAT;
                                                                         return NUMBER;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 254 "lexer.l"
{sscanf(yytext,"%Lf",&yylval.number.doub_number);
                                                                         yylval.number.num_numberspec = C_REAL;
                                                                         yylval.number.num_sizespec = C_LONGDOUBLE;
                                                                         return NUMBER;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 259 "lexer.l"
{sscanf(yytext, "%Lf", &yylval.number.doub_number);
                                 yylval.number.num_numberspec = C_REAL;
                                 yylval.number.num_sizespec = C_DOUBLE;
                                 return NUMBER;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 264 "lexer.l"
{sscanf(yytext, "%Lf", &yylval.number.doub_number);
                                     yylval.number.num_numberspec = C_REAL;
                                     yylval.number.num_sizespec = C_FLOAT;
                                     return NUMBER;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 269 "lexer.l"
{sscanf(yytext, "%Lf", &yylval.number.doub_number);
                                     yylval.number.num_numberspec = C_REAL;
                                     yylval.number.num_sizespec = C_DOUBLE;
                                     return NUMBER;}
	YY_BREAK

    // CHARACTER LITERALS / CONSTANTS

case 70:
YY_RULE_SETUP
#line 276 "lexer.l"
{BEGIN(BEGIN_CHAR); char_size = 0; char_ind = char_buffer;}
	YY_BREAK

case 71:
YY_RULE_SETUP
#line 278 "lexer.l"
{BEGIN(INITIAL);
         if (char_size == 0){
            yylval.char_lit.actual_char = '\0';
         }else{
            if (char_size > 1){
                fprintf(stderr,"%s:%d:Warning:Unsupported multibyte character literal truncated to first byte\n", fname, line_num);
            }
            yylval.char_lit.actual_char = char_buffer[0];   
         }
         return CHARLIT;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 288 "lexer.l"
{*char_ind = '\0'; char_size++; char_ind++;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 289 "lexer.l"
{*char_ind = '\a'; char_size++; char_ind++;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 290 "lexer.l"
{*char_ind = '\b'; char_size++; char_ind++;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 291 "lexer.l"
{*char_ind = '\f'; char_size++; char_ind++;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 292 "lexer.l"
{*char_ind = '\n'; char_size++; char_ind++;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 293 "lexer.l"
{*char_ind = '\r'; char_size++; char_ind++;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 294 "lexer.l"
{*char_ind = '\t'; char_size++; char_ind++;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 295 "lexer.l"
{*char_ind = '\v'; char_size++; char_ind++;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 296 "lexer.l"
{*char_ind = '\''; char_size++; char_ind++;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 297 "lexer.l"
{*char_ind = '"'; char_size++; char_ind++;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 298 "lexer.l"
{*char_ind = '\\'; char_size++; char_ind++;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 299 "lexer.l"
{*char_ind = '?';  char_size++; char_ind++;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 300 "lexer.l"
{
                        unsigned int oct_num = (unsigned int)strtol(yytext+1, &yytext+sizeof(yytext),8);
                        if (oct_num> 0xff){
                            fprintf(stderr,"%s:%d:Warning:Oct escape sequence \\%03o out of range\n", fname, line_num, oct_num);
                        }
                        *char_ind = (char) oct_num;
                        char_size++;
                        char_ind++;
                    }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 310 "lexer.l"
{
                        unsigned int hex_num = (unsigned int) strtol(yytext+2, &yytext+sizeof(yytext),16);
                        if (hex_num > 0xff){
                            fprintf(stderr,"%s:%d:Warning:Hex escape sequence \\x%02x out of range\n",fname, line_num, hex_num);
                        }
                        *char_ind = (char) hex_num;
                        char_size++;
                        char_ind++;
                    }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 319 "lexer.l"
{*char_ind = yytext[0];char_ind++;char_size++;}
	YY_BREAK


    // STRING LITERALS

case 87:
YY_RULE_SETUP
#line 325 "lexer.l"
{BEGIN(BEGIN_STR); char_ind = char_buffer; yylval.string_lit.string_size = 0;}
	YY_BREAK

case 88:
YY_RULE_SETUP
#line 328 "lexer.l"
{BEGIN(INITIAL);
         yylval.string_lit.string_literal = (char*) malloc(yylval.string_lit.string_size+1);
         memcpy(yylval.string_lit.string_literal, char_buffer, yylval.string_lit.string_size);
         return STRING;
        }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 333 "lexer.l"
{*char_ind = '\0'; yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 334 "lexer.l"
{*char_ind = '\a'; yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 335 "lexer.l"
{*char_ind = '\b'; yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 336 "lexer.l"
{*char_ind = '\f'; yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 337 "lexer.l"
{*char_ind = '\n'; yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 338 "lexer.l"
{*char_ind = '\r'; yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 339 "lexer.l"
{*char_ind = '\t'; yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 340 "lexer.l"
{*char_ind = '\v'; yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 341 "lexer.l"
{*char_ind = '\''; yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 342 "lexer.l"
{*char_ind = '"' ; yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 343 "lexer.l"
{*char_ind = '\\'; yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 344 "lexer.l"
{*char_ind = '?';  yylval.string_lit.string_size++; char_ind++;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 345 "lexer.l"
{
                        unsigned int oct_num = (unsigned int)strtol(yytext+1, &yytext+sizeof(yytext),8);
                        if (oct_num> 0xff){
                            fprintf(stderr,"%s:%d:Warning:Oct escape sequence \\%03o out of range\n", fname, line_num, oct_num);
                            oct_num = 0xff;
                        }
                        *char_ind = (char) oct_num;
                        char_ind++;
                        yylval.string_lit.string_size++;
                    }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 356 "lexer.l"
{
                        unsigned int hex_num = (unsigned int) strtol(yytext+2, &yytext+sizeof(yytext),16);
                        if (hex_num > 0xff){
                            fprintf(stderr,"%s:%d:Warning:Hex escape sequence \\x%02x out of range\n",fname, line_num, hex_num);
                            hex_num = 0xff;
                        }
                        *char_ind =  (char) hex_num;
                        char_ind++;
                        yylval.string_lit.string_size++;
                    }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 366 "lexer.l"
{*char_ind = (char)yytext[0];char_ind++; yylval.string_lit.string_size++;}
	YY_BREAK


    // OPERATORS

case 104:
YY_RULE_SETUP
#line 375 "lexer.l"
{return '+';}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 376 "lexer.l"
{return '-';}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 377 "lexer.l"
{return '{';}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 378 "lexer.l"
{return '}';}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 379 "lexer.l"
{return '(';}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 380 "lexer.l"
{return ')';}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 381 "lexer.l"
{return '.';}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 382 "lexer.l"
{return ']';}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 383 "lexer.l"
{return '&';}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 384 "lexer.l"
{return '*';}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 385 "lexer.l"
{return '~';}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 386 "lexer.l"
{return '!';}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 387 "lexer.l"
{return '/';}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 388 "lexer.l"
{return '%';}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 389 "lexer.l"
{return '<';}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 390 "lexer.l"
{return '>';}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 391 "lexer.l"
{return '^';}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 392 "lexer.l"
{return '|';}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 393 "lexer.l"
{return '?';}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 394 "lexer.l"
{return ':';}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 395 "lexer.l"
{return ';';}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 396 "lexer.l"
{return '=';}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 397 "lexer.l"
{return ',';}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 398 "lexer.l"
{return '#';}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 399 "lexer.l"
{return INDSEL;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 400 "lexer.l"
{return PLUSPLUS;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 401 "lexer.l"
{return MINUSMINUS;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 402 "lexer.l"
{return SHL;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 403 "lexer.l"
{return SHR;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 404 "lexer.l"
{return LTEQ;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 405 "lexer.l"
{return GTEQ;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 406 "lexer.l"
{return EQEQ;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 407 "lexer.l"
{return NOTEQ;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 408 "lexer.l"
{return LOGAND;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 409 "lexer.l"
{return LOGOR;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 410 "lexer.l"
{return ELLIPSIS;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 411 "lexer.l"
{return TIMESEQ;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 412 "lexer.l"
{return DIVEQ;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 413 "lexer.l"
{return MODEQ;}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 414 "lexer.l"
{return PLUSEQ;}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 415 "lexer.l"
{return MINUSEQ;}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 416 "lexer.l"
{return SHLEQ;}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 417 "lexer.l"
{return SHREQ;}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 418 "lexer.l"
{return ANDEQ;}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 419 "lexer.l"
{return OREQ;}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 420 "lexer.l"
{return XOREQ;}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 422 "lexer.l"
{return '[';}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 423 "lexer.l"
{strtok(yytext," \"");
                   line_num = atoi(strtok(NULL, " \"")) -1; 
                   char* temp=strtok(NULL," \""); 
                   fname = realloc(fname, strlen(temp)+1);
                   strncpy(fname,temp, strlen(temp)+1);}  
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 428 "lexer.l"
{} 
	YY_BREAK
case 153:
/* rule 153 can match eol */
YY_RULE_SETUP
#line 429 "lexer.l"
{line_num++;}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 430 "lexer.l"
{fprintf(stderr, "%s:%d: Error: unrecognized character '%s'\n", fname, line_num,yytext);exit(-1);}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 431 "lexer.l"
ECHO;
	YY_BREAK
#line 2000 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BEGIN_CHAR):
case YY_STATE_EOF(BEGIN_STR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 335 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 335 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 334);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 431 "lexer.l"



void printChar(char ch){
    switch(ch){
        case '\0':
            fprintf(stdout,"\\0");
            break;
        case '\a':
            fprintf(stdout,"\\a");
            break;
        case '\b':
            fprintf(stdout,"\\b");
            break;
        case '\f':
            fprintf(stdout, "\\f");
            break;
        case '\n':
            fprintf(stdout,"\\n");
            break;
        case '\r':
            fprintf(stdout,"\\r");
            break;
        case '\t':
            fprintf(stdout,"\\t");
            break;
        case '\v':
            fprintf(stdout,"\\v");
            break;
        case '\'':
            fprintf(stdout,"\\\'");
            break;
        case '\"':
            fprintf(stdout,"\\\"");
            break;
        case '\\':
            fprintf(stdout,"\\");
            break;
        default:
            if (ch < 177 && ch > 31){
                fprintf(stdout,"%c",ch);
            }else{
                fprintf(stdout,"\\%03o", (unsigned char)ch);
            }
            break;
    }
}

/*int main(int argc, char *argv[]){
    int t;
    FILE *fd;
    char *ptr;
    ssize_t ret;
    char * line = NULL;
    size_t len = 0;
    int str_size;
    fd = fopen(argv[1], "r");
    yyin = fd;
    while (t = yylex()){
        if (t < 257 && t > 0){
            fprintf(stdout, "%s\t%d\t%c\t\n", fname, line_num, t);
            
        }else if (t == IDENT){      // 257
            fprintf(stdout, "%s\t%d\tIDENT\t%s\n", fname, line_num, yylval.ident_name);
            free(yylval.ident_name);
        }else if (t == CHARLIT){    // 258
            fprintf(stdout,"%s\t%d\tCHARLIT\t",fname, line_num);
            printChar(yylval.actual_char);
            fprintf(stdout,"\n");
        }else if (t == STRING){     // 259
            fprintf(stdout,"%s\t%d\tSTRING\t", fname, line_num);
            ptr = yylval.string_literal;
            str_size = 0;
            while (str_size < yylval.string_size){
                printChar(*ptr);
                ptr++;
                str_size++;
            }
            printf("\n");
            free(yylval.string_literal);
        }else if (t == NUMBER){     // 260
            fprintf(stdout, "%s\t%d\tNUMBER\t", fname, line_num);
            if (yylval.num_numberspec == C_INTEGER){
                fprintf(stdout,"INTEGER\t%llu\t", yylval.number);
                if (yylval.num_unsigned == 1){
                    fprintf(stdout,"UNSIGNED,");
                }
                if (yylval.num_sizespec == C_INT){
                    fprintf(stdout,"INT\n");
                }else if (yylval.num_sizespec == C_LONGLONG){
                    fprintf(stdout,"LONGLONG\n");
                }else{
                    fprintf(stdout,"LONG\n");
                }
            }else{
                fprintf(stdout,"REAL\t%Lg\t", yylval.doub_number);
                if(yylval.num_sizespec == C_DOUBLE){
                    fprintf(stdout,"DOUBLE\n");
                }else if (yylval.num_sizespec == C_LONGDOUBLE){
                    fprintf(stdout, "LONGDOUBLE\n");
                }else{
                    fprintf(stdout, "FLOAT\n");
                }
            }
        }else if (t >= INDSEL && t <= _IMAGINARY){//261 - 321
            fprintf(stdout,"%s\t%d\t%s\t\n",fname, line_num, tokens_names[t-261]);
        }else if (t == TOKEOF){
            fprintf(stdout, "%s\t%d\tTOKEOF\t\n",fname, line_num);
        }
    }

}*/

